@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Maria da Cruz",
    "email": "maria.cruz@gmail.com",
    "password": "jfsdifosdofsi"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "maria.cruz@gmail.com",
    "password": "jfsdifosdofsi"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "How to install docker",
    "content": "You can install by rpm packeges on in packege manager"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=3
Content-Type: application/json
Authorization: Bearer {{authToken}}
