@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Maria da Cruz",
    "email": "maria.cruz@gmail.com",
    "password": "jfsdifosdofsi"
}

### 

# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "maria.cruz@gmail.com",
    "password": "jfsdifosdofsi"
}