@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Lisa Sypsom",
    "email": "lisa.yspsom@gmail.com",
    "password": "jfsdifosdofsi"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "lisa.yspsom@gmail.com",
    "password": "jfsdifosdofsi"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Undestending nest dependence injection",
    "content": "Actuelly it's scarey",
    "attachments": []
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name upload_file
POST {{baseUrl}}/attachments
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ./test/e2e/test.png
--MfnBoundry--

###

# @name create_answer
POST {{baseUrl}}/questions/7482b20a-e81f-4897-95f8-8be1392c4296/answer
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "attachments": [],
    "content": "Actuelly it's scarey"
}