version: '3.8'

services: 
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    network_mode: host
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/usr/data/postgres

  cache:
    container_name: nest-clean-cache
    image: redis
    network_mode: host
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/usr/data

  api:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    restart: always
    env_file: .env
    network_mode: host
    environment:
      - DATABASE_URL=$DATABASE_URL
      - JWT_SECRET=$JWT_SECRET
      - JWT_PUBLIC_KEY=$JWT_PUBLIC_KEY
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
      - cache

volumes:
  postgres:
    name: postgres
  cache:
    name: redis